<?php

/**
 * @file
 * Generate custom thumbnails for jp2 media entities.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * {@inheritDoc}
 */
function media_thumbnails_jp2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.media_thumbnails_jp2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Media Thumbnails jp2 module generates thumbnails for jp2 media entities.') . '</p>';
      return $output;
  }
}
